import json
import os

zh_additions = {
  "wardrobeEmpty": "衣橱为空，点击 + 添加衣物",
  "all": "全部",
  "top": "上装",
  "bottom": "下装",
  "shoes": "鞋履",
  "accessory": "配饰",
  "outerwear": "外套",
  "addClothing": "添加衣物",
  "pleaseEnterClothingName": "请输入衣物名称",
  "color": "颜色",
  "material": "材质",
  "brand": "品牌",
  "season": "季节",
  "category": "分类",
  "saveToWardrobe": "保存到衣橱",
  "selectCategory": "选择分类",
  "selectSeason": "请选择适用季节",
  "selectColor": "请选择衣物颜色",
  "clothingDetails": "衣物详情",
  "spring": "春季",
  "summer": "夏季",
  "autumn": "秋季",
  "winter": "冬季",
  "fourSeasons": "四季",
  "confirmDelete": "确认删除",
  "confirmDeleteClothing": "确定要删除这件衣物吗？",
  "cancel": "取消",
  "delete": "删除",
  "edit": "编辑",
  "save": "保存",
  "customOutfit": "定制穿搭",
  "yourOutfitNeeds": "您的搭配需求？",
  "date": "日期",
  "location": "地点",
  "activity": "活动",
  "people": "人物",
  "getOutfitPlan": "获取搭配方案",
  "today": "今天",
  "tomorrow": "明天",
  "dayAfterTomorrow": "后天",
  "thisWeekend": "周末",
  "nextWeek": "下周",
  "workday": "工作日",
  "indoor": "室内",
  "outdoor": "户外",
  "office": "办公室",
  "mall": "商场",
  "park": "公园",
  "cafe": "咖啡厅",
  "daily": "日常",
  "leisure": "休闲",
  "meeting": "开会",
  "dateActivity": "约会",
  "sports": "运动",
  "birthdayParty": "生日聚会",
  "formalDinner": "正式晚宴",
  "partner": "伴侣",
  "friends": "朋友",
  "colleagues": "同事",
  "family": "家人",
  "client": "客户",
  "custom": "自定义",
  "enterCustomContent": "请输入自定义内容",
  "confirm": "确认",
  "shareOutfit": "分享穿搭",
  "saveShareImage": "保存/分享图片",
  "todayOutfitRecommendation": "我的今日穿搭推荐",
  "todayWeather": "今日天气",
  "matchPercentage": "匹配度",
  "generatingOutfit": "正在为您定制专属穿搭...",
  "fashionItem": "时尚单品",
  "alternativePlan": "备选方案",
  "noMatchingClothing": "没有找到匹配的衣物",
  "searchClothing": "搜索衣物..."
}

en_additions = {
  "wardrobeEmpty": "Wardrobe is empty, tap + to add items",
  "all": "All",
  "top": "Top",
  "bottom": "Bottom",
  "shoes": "Shoes",
  "accessory": "Accessory",
  "outerwear": "Outerwear",
  "addClothing": "Add Item",
  "pleaseEnterClothingName": "Please enter item name",
  "color": "Color",
  "material": "Material",
  "brand": "Brand",
  "season": "Season",
  "category": "Category",
  "saveToWardrobe": "Save to Wardrobe",
  "selectCategory": "Select Category",
  "selectSeason": "Select Season",
  "selectColor": "Select Color",
  "clothingDetails": "Item Details",
  "spring": "Spring",
  "summer": "Summer",
  "autumn": "Autumn",
  "winter": "Winter",
  "fourSeasons": "All Seasons",
  "confirmDelete": "Confirm Delete",
  "confirmDeleteClothing": "Are you sure you want to delete this item?",
  "cancel": "Cancel",
  "delete": "Delete",
  "edit": "Edit",
  "save": "Save",
  "customOutfit": "Custom Outfit",
  "yourOutfitNeeds": "What are your outfit needs?",
  "date": "Date",
  "location": "Location",
  "activity": "Activity",
  "people": "People",
  "getOutfitPlan": "Get Outfit Plan",
  "today": "Today",
  "tomorrow": "Tomorrow",
  "dayAfterTomorrow": "Day After Tomorrow",
  "thisWeekend": "Weekend",
  "nextWeek": "Next Week",
  "workday": "Workday",
  "indoor": "Indoor",
  "outdoor": "Outdoor",
  "office": "Office",
  "mall": "Mall",
  "park": "Park",
  "cafe": "Cafe",
  "daily": "Daily",
  "leisure": "Leisure",
  "meeting": "Meeting",
  "dateActivity": "Date",
  "sports": "Sports",
  "birthdayParty": "Birthday Party",
  "formalDinner": "Formal Dinner",
  "partner": "Partner",
  "friends": "Friends",
  "colleagues": "Colleagues",
  "family": "Family",
  "client": "Client",
  "custom": "Custom",
  "enterCustomContent": "Enter custom detail",
  "confirm": "Confirm",
  "shareOutfit": "Share Outfit",
  "saveShareImage": "Save/Share Image",
  "todayOutfitRecommendation": "My Today Outfit Recommendation",
  "todayWeather": "Today's Weather",
  "matchPercentage": "Match",
  "generatingOutfit": "Generating your custom outfit...",
  "fashionItem": "Fashion Item",
  "alternativePlan": "Alternative Plan",
  "noMatchingClothing": "No matching clothes found",
  "searchClothing": "Search clothing..."
}

def update_arb(file_path, additions):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    for k, v in additions.items():
        data[k] = v
        
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

if __name__ == '__main__':
    update_arb('lib/l10n/app_zh.arb', zh_additions)
    update_arb('lib/l10n/app_en.arb', en_additions)
    print("ARB files updated.")
